# -*- coding: utf-8 -*-
"""RESTAURANT_REVIEW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYiTsxSH7qy7UhlxZ797-08nm0vgH708
"""

import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_excel("Restaurant reviews.xlsx")
df.head()

df['Rating'] = df['Rating'].astype(str).str.extract('(\d)').astype(float)

def make_label(r):
    if r >= 4:
        return "Positive"
    elif r == 3:
        return "Neutral"
    else:
        return "Negative"

df['Sentiment'] = df['Rating'].apply(make_label)

df[['Rating','Sentiment']].head()
df['Sentiment'].value_counts()

nltk.download('stopwords')
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_review(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]
    return " ".join(words)

df['Cleaned_Review'] = df['Review'].apply(clean_review)

df['Review'] = df['Review'].fillna('')
df['Review'] = df['Review'].astype(str)
df['Cleaned_Review'] = df['Review'].apply(clean_review)
df[['Review','Cleaned_Review']].head()

sns.countplot(x='Sentiment', data=df)
plt.title("Sentiment Distribution")
plt.show()

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['Cleaned_Review'])
y = df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

nb = MultinomialNB()
nb.fit(X_train, y_train)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

nb_pred = nb.predict(X_test)
lr_pred = lr.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))
print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))

cm = confusion_matrix(y_test, lr_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix (Logistic Regression)")
plt.show()

